// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/alerts" | "/[locale]/alerts/[slug]" | "/[locale]/announcements" | "/[locale]/announcements/[slug]" | "/[locale]/contacts" | "/[locale]/documents" | "/[locale]/guides" | "/[locale]/guides/[slug]" | "/[locale]/leadership" | "/[locale]/map" | "/[locale]/news" | "/[locale]/news/[slug]" | "/[locale]/pages/[slug]" | "/[locale]/projects" | "/[locale]/projects/[slug]" | "/[locale]/search" | "/[locale]/sitemap" | "/[locale]/sos" | "/[locale]/structure" | "/[locale]/symbols"
type AppRouteHandlerRoutes = "/api/revalidate"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/alerts": { "locale": string; }
  "/[locale]/alerts/[slug]": { "locale": string; "slug": string; }
  "/[locale]/announcements": { "locale": string; }
  "/[locale]/announcements/[slug]": { "locale": string; "slug": string; }
  "/[locale]/contacts": { "locale": string; }
  "/[locale]/documents": { "locale": string; }
  "/[locale]/guides": { "locale": string; }
  "/[locale]/guides/[slug]": { "locale": string; "slug": string; }
  "/[locale]/leadership": { "locale": string; }
  "/[locale]/map": { "locale": string; }
  "/[locale]/news": { "locale": string; }
  "/[locale]/news/[slug]": { "locale": string; "slug": string; }
  "/[locale]/pages/[slug]": { "locale": string; "slug": string; }
  "/[locale]/projects": { "locale": string; }
  "/[locale]/projects/[slug]": { "locale": string; "slug": string; }
  "/[locale]/search": { "locale": string; }
  "/[locale]/sitemap": { "locale": string; }
  "/[locale]/sos": { "locale": string; }
  "/[locale]/structure": { "locale": string; }
  "/[locale]/symbols": { "locale": string; }
  "/api/revalidate": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
