// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[locale]/alerts/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/alerts/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/alerts/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/alerts">> = Specific
  const handler = {} as typeof import("../../app/[locale]/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/announcements/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/announcements/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/announcements/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/announcements">> = Specific
  const handler = {} as typeof import("../../app/[locale]/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contacts">> = Specific
  const handler = {} as typeof import("../../app/[locale]/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/documents">> = Specific
  const handler = {} as typeof import("../../app/[locale]/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/guides/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/guides/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/guides/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/guides">> = Specific
  const handler = {} as typeof import("../../app/[locale]/guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/leadership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/leadership">> = Specific
  const handler = {} as typeof import("../../app/[locale]/leadership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/map">> = Specific
  const handler = {} as typeof import("../../app/[locale]/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/news/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/news">> = Specific
  const handler = {} as typeof import("../../app/[locale]/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/pages/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pages/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/pages/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/projects">> = Specific
  const handler = {} as typeof import("../../app/[locale]/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/search">> = Specific
  const handler = {} as typeof import("../../app/[locale]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/sitemap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sitemap">> = Specific
  const handler = {} as typeof import("../../app/[locale]/sitemap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/sos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sos">> = Specific
  const handler = {} as typeof import("../../app/[locale]/sos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/structure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/structure">> = Specific
  const handler = {} as typeof import("../../app/[locale]/structure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[locale]/symbols/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/symbols">> = Specific
  const handler = {} as typeof import("../../app/[locale]/symbols/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
