/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service health status */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service readiness status */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get homepage aggregate content */
        get: operations["getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site navigation menus */
        get: operations["getMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search across public content
         * @description Additionally throttled to 60 requests per minute.
         */
        get: operations["getSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List news articles */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single news article */
        get: operations["getNewsBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pages */
        get: operations["getPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single page */
        get: operations["getPageBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List content categories */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List safety instructions */
        get: operations["getInstructions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single safety instruction */
        get: operations["getInstructionBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["getDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["getProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single project */
        get: operations["getProjectBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List announcements */
        get: operations["getAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/announcements/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single announcement */
        get: operations["getAnnouncementBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a public contact/report form
         * @description Additionally throttled to 10 requests per minute.
         */
        post: operations["postSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active and recent alerts
         * @description Not paginated.
         */
        get: operations["getAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current active-alerts snapshot by region */
        get: operations["getAlertsActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single alert */
        get: operations["getAlertBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List region alert statuses
         * @description Not paginated. Items reuse the same shape as alerts/active regions.
         */
        get: operations["getRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List regional office directory entries */
        get: operations["getRegionsDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginationLinksStandard: {
            first: string | null;
            last: string | null;
            prev: string | null;
            next: string | null;
        };
        PaginationMetaLinkItem: {
            url: string | null;
            label: string;
            page: number | null;
            active: boolean;
        };
        PaginationMetaStandard: {
            current_page: number;
            from: number | null;
            last_page: number;
            links: components["schemas"]["PaginationMetaLinkItem"][];
            path: string;
            per_page: number;
            to: number | null;
            total: number;
        };
        PaginationLinksMinimal: {
            prev: string | null;
            next: string | null;
        };
        PaginationMetaMinimal: {
            current_page: number;
            last_page: number;
            per_page: number;
            total: number;
        };
        SeoFields: {
            title: string;
            description: string;
        };
        AlertRegionStatus: {
            key: string;
            name: string;
            /** @enum {string} */
            level: "none" | "info" | "warning" | "danger" | "critical";
            count: number;
            statusText: string;
        };
        AlertRegionRef: {
            code: string;
            name: string;
        };
        AlertMetaEntry: {
            label: string;
            value: string;
        };
        AlertSummary: {
            slug: string;
            /** @enum {string} */
            level: "info" | "warning" | "danger" | "critical";
            level_label: string;
            /** @enum {string} */
            severity: "info" | "attention" | "warning" | "danger" | "critical";
            status: string;
            /** @enum {string} */
            status_code: "active" | "completed";
            is_active: boolean;
            /** @enum {string} */
            hazard: "mudflow" | "earthquake" | "flood" | "avalanche" | "fire" | "wind" | "heat" | "frost" | "landslide" | "storm";
            hazard_label: string;
            title: string;
            summary: string;
            region: string;
            region_codes: string[];
            datetime: string | null;
            starts_at: string | null;
            ends_at: string | null;
            published_at: string | null;
            starts_at_iso: string | null;
            ends_at_iso: string | null;
        };
        AlertDetail: components["schemas"]["AlertSummary"] & {
            body: string;
            instructions: string[];
            contacts: string;
            source: string | null;
            /** @enum {string} */
            territory_type: "country" | "regions";
            regions: components["schemas"]["AlertRegionRef"][];
            meta: components["schemas"]["AlertMetaEntry"][];
        };
        AlertActiveSnapshot: {
            /** @enum {string} */
            state: "calm" | "warning" | "critical";
            count: number;
            regions: components["schemas"]["AlertRegionStatus"][];
        };
        AnnouncementItem: {
            slug: string;
            /** @enum {string} */
            kind: "vacancy" | "tender";
            kind_label: string;
            title: string;
            org: string | null;
            desc: string;
            deadline: string;
            deadline_at: string | null;
            /** @enum {string} */
            deadline_state: "unlimited" | "open" | "closed";
            open: boolean;
            application_url: string | null;
        };
        DocumentFile: {
            /** @enum {string} */
            lang: "tg" | "ru" | "en";
            /** @enum {string} */
            label: "ТҶ" | "РУ" | "EN";
            url: string;
            ext: string;
            size: string;
            size_bytes: number;
        };
        DocumentItem: {
            id: number;
            type: string;
            /** @enum {string} */
            type_value: "law" | "resolution" | "order" | "report" | "plan" | "norm" | "instruction" | "open_data" | "form";
            title: string;
            number: string | null;
            section: string | null;
            date: string | null;
            date_iso: string | null;
            lang: string;
            size: string | null;
            href: string | null;
            files: components["schemas"]["DocumentFile"][];
        };
        InstructionSections: {
            before: string[];
            during: string[];
            after: string[];
            prohibited: string[];
        };
        InstructionSummary: {
            slug: string;
            title: string;
            summary: string;
            /** @enum {string|null} */
            hazard: "mudflow" | "earthquake" | "flood" | "avalanche" | "fire" | "wind" | "heat" | "frost" | "landslide" | "storm" | null;
            hazard_label: string | null;
            /** @enum {string|null} */
            hazard_icon: "waves" | "activity" | "mountain-snow" | "flame" | "wind" | "thermometer-sun" | "snowflake" | "mountain" | null;
            priority: boolean;
            image: string | null;
            image_srcset: string | null;
        };
        InstructionDetail: components["schemas"]["InstructionSummary"] & {
            sections: components["schemas"]["InstructionSections"];
            body: string;
        };
        NewsSummary: {
            slug: string;
            title: string;
            excerpt: string;
            category: string | null;
            date: string | null;
            datetime: string | null;
            image: string | null;
            image_srcset: string | null;
            featured: boolean;
        };
        NewsDetail: components["schemas"]["NewsSummary"] & {
            body: string;
            views: number;
            seo: components["schemas"]["SeoFields"];
        };
        PageSummary: {
            slug: string;
            title: string;
        };
        PageDetail: components["schemas"]["PageSummary"] & {
            body: string;
            seo: components["schemas"]["SeoFields"];
            updated: string | null;
            updated_at: string | null;
        };
        ProjectSummary: {
            slug: string;
            title: string;
            status: string;
            /** @enum {string} */
            status_code: "preparation" | "implementing" | "completed";
            /** @enum {string} */
            status_tone: "info" | "success" | "neutral";
            years: string | null;
            partner: string | null;
            budget: string | null;
            desc: string;
            image: string | null;
            image_srcset: string | null;
        };
        ProjectDetail: components["schemas"]["ProjectSummary"] & {
            code: string | null;
            customer: string | null;
            body: string;
            goals: string[];
            /** @description Raw JSON passthrough, not strictly validated. Items typically look like {date, text, tone} where tone is one of success, info, warning, danger, neutral when present. */
            timeline: Record<string, never>[];
            direction: {
                address: string | null;
                phone: string | null;
                email: string | null;
            };
        };
        CategoryItem: {
            slug: string;
            name: string;
            type: string;
        };
        RegionDirectoryItem: {
            code: string;
            name: string;
            type: string;
            /** @enum {string} */
            type_code: "city" | "oblast" | "gbao" | "rrp";
            head: string;
            regional_center: string | null;
            address: string;
            phone: string | null;
            phone_href: string | null;
            duty_phone: string | null;
            email: string | null;
            districts_count: number;
            districts: string[];
        };
        SearchResultItem: {
            /** @enum {string} */
            type: "news" | "alert" | "instruction" | "document" | "project" | "announcement" | "page";
            title: string;
            excerpt: string;
            path: string;
            published_at: string | null;
        };
        HomeResponse: {
            blocks: {
                type: string;
                title: string;
                config: {
                    [key: string]: unknown;
                } | unknown[];
            }[];
            alerts: {
                state: string;
                count: number;
                regions: components["schemas"]["AlertRegionStatus"][];
                items: components["schemas"]["AlertSummary"][];
            };
            news: components["schemas"]["NewsSummary"][];
            instructions: components["schemas"]["InstructionSummary"][];
            documents: components["schemas"]["DocumentItem"][];
            announcements: components["schemas"]["AnnouncementItem"][];
            projects: components["schemas"]["ProjectSummary"][];
            emergency_contacts: {
                emergency_number: string;
                trust_phone: string | null;
                duty_phone: string | null;
                email: string | null;
                services: {
                    num: string;
                    label: string;
                }[];
            };
        };
        SettingsResponse: {
            data: {
                org: {
                    name: string;
                    short_name: string;
                    about: string;
                    address: string;
                    email: string | null;
                    emergency_number: string;
                    trust_phone: string | null;
                };
                contacts: {
                    press_email: string | null;
                    press_phone: string | null;
                    duty_phone: string | null;
                };
                social: {
                    [key: string]: string;
                };
                structure: {
                    founded_year: string;
                    units_count: string;
                };
                emergency_services: {
                    num: string;
                    label: string;
                }[];
                copyright: string;
                seo: {
                    meta_title: string;
                    meta_description: string;
                };
            };
            meta: {
                requested_locale: string;
                resolved_locale: string;
                fallback_used: boolean;
                available_locales: string[];
            };
        };
        MenuTreeItem: {
            label: string;
            url: string | null;
            children: {
                label: string;
                url: string | null;
            }[];
        };
        MenuResponse: {
            data: {
                main: components["schemas"]["MenuTreeItem"][];
                footer: components["schemas"]["MenuTreeItem"][];
            };
        };
        SubmissionRequestBody: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string | null;
            topic?: string | null;
            region_id?: number | null;
            message: string;
            consent: boolean | string;
            /** @description Leave empty; anti-spam honeypot field. */
            website?: string;
        };
        SubmissionResponse: {
            tracking_number: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            service: string;
            version: string;
            checks: {
                database: boolean;
            };
            timestamp: string;
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            checks: {
                database: boolean;
                storage: boolean;
                scheduler: boolean;
                queue_connection: string;
            };
            scheduler_last_run: string | null;
            timestamp: string;
        };
        ValidationErrorResponse: {
            message: string;
            errors: {
                [key: string]: string[];
            };
        };
        NotFoundResponse: {
            message: string;
        };
        InstructionEnvelope: {
            data: components["schemas"]["InstructionSummary"][];
            links: components["schemas"]["PaginationLinksStandard"];
            meta: components["schemas"]["PaginationMetaStandard"];
        };
        PageEnvelope: {
            data: components["schemas"]["PageSummary"][];
            links: components["schemas"]["PaginationLinksStandard"];
            meta: components["schemas"]["PaginationMetaStandard"];
        };
        DocumentEnvelope: {
            data: components["schemas"]["DocumentItem"][];
            links: components["schemas"]["PaginationLinksStandard"];
            meta: components["schemas"]["PaginationMetaStandard"];
        };
        ProjectEnvelope: {
            data: components["schemas"]["ProjectSummary"][];
            links: components["schemas"]["PaginationLinksStandard"];
            meta: components["schemas"]["PaginationMetaStandard"];
        };
        AnnouncementEnvelope: {
            data: components["schemas"]["AnnouncementItem"][];
            links: components["schemas"]["PaginationLinksStandard"];
            meta: components["schemas"]["PaginationMetaStandard"];
        };
        NewsEnvelope: {
            data: components["schemas"]["NewsSummary"][];
            meta: {
                total: number;
                per_page: number;
                current_page: number;
                last_page: number;
            };
        };
        SearchEnvelope: {
            data: components["schemas"]["SearchResultItem"][];
            meta: components["schemas"]["PaginationMetaMinimal"];
            links: components["schemas"]["PaginationLinksMinimal"];
        };
        CategoryEnvelope: {
            data: components["schemas"]["CategoryItem"][];
            meta: components["schemas"]["PaginationMetaMinimal"];
            links: components["schemas"]["PaginationLinksMinimal"];
        };
        RegionDirectoryEnvelope: {
            data: components["schemas"]["RegionDirectoryItem"][];
            meta: components["schemas"]["PaginationMetaMinimal"];
            links: components["schemas"]["PaginationLinksMinimal"];
        };
    };
    responses: never;
    parameters: {
        /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
        LocaleParam: "tg" | "ru" | "en";
        /** @description 1-indexed page number. */
        PageParam: number;
        /** @description Items per page. Server-side capped regardless of the value requested. */
        PerPageParam: number;
        /** @description Search text, minimum 2 characters. */
        SearchQueryParam: string;
        /** @description Filters categories by type. An explicit empty string means "no filter" (returns categories of every type) rather than falling back to the default. */
        CategoryTypeParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service is unhealthy (e.g. database unreachable) — same body shape as 200 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service is not ready (database/storage/scheduler check failing) — same body shape as 200 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    getHome: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Homepage aggregate content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HomeResponse"];
                    };
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    getMenu: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site navigation menus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponse"];
                };
            };
        };
    };
    getSearch: {
        parameters: {
            query: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description Search text, minimum 2 characters. */
                q: components["parameters"]["SearchQueryParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchEnvelope"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    getNews: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of news articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsEnvelope"];
                };
            };
        };
    };
    getNewsBySlug: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description News article detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NewsDetail"];
                    };
                };
            };
            /** @description News article not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    getPages: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"];
                };
            };
        };
    };
    getPageBySlug: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PageDetail"];
                    };
                };
            };
            /** @description Page not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description Filters categories by type. An explicit empty string means "no filter" (returns categories of every type) rather than falling back to the default. */
                type?: components["parameters"]["CategoryTypeParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEnvelope"];
                };
            };
        };
    };
    getInstructions: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of safety instructions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructionEnvelope"];
                };
            };
        };
    };
    getInstructionBySlug: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instruction detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["InstructionDetail"];
                    };
                };
            };
            /** @description Instruction not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    getDocuments: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEnvelope"];
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEnvelope"];
                };
            };
        };
    };
    getProjectBySlug: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectDetail"];
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    getAnnouncements: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of announcements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementEnvelope"];
                };
            };
        };
    };
    getAnnouncementBySlug: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Announcement detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AnnouncementItem"];
                    };
                };
            };
            /** @description Announcement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    postSubmission: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequestBody"];
            };
        };
        responses: {
            /** @description Submission accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    getAlerts: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertSummary"][];
                    };
                };
            };
        };
    };
    getAlertsActive: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active alerts snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertActiveSnapshot"];
                    };
                };
            };
        };
    };
    getAlertBySlug: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertDetail"];
                    };
                };
            };
            /** @description Alert not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
    getRegions: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of region alert statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertRegionStatus"][];
                    };
                };
            };
        };
    };
    getRegionsDirectory: {
        parameters: {
            query?: {
                /** @description Resolves content locale. Falls back to Accept-Language header negotiation (ru, tg, en preference order), then to ru. Any value outside {tg,ru,en} is silently ignored (not a 422/400) and resolution falls through to the header/default. */
                locale?: components["parameters"]["LocaleParam"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["PageParam"];
                /** @description Items per page. Server-side capped regardless of the value requested. */
                per_page?: components["parameters"]["PerPageParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated regional office directory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionDirectoryEnvelope"];
                };
            };
        };
    };
}
